### PR TITLE
Add more examples of Kadi4mat

### PR DESCRIPTION
**Pull request by jmanideep**

### CODE REVIEW

**Comment by jmanideep** [comment]
I don't see that. `@` is there in front of `context` in both metadata files in `collections-example.eln` and `records-example.eln` too.

**Comment by NicolasCARPi** [comment]
Yes, you're right, not sure where I saw that then! Nevermind.

**Comment by jmanideep** [comment]
I think `@` in front of `context` might be missing in my previous example.

**Comment by NicolasCARPi** [comment]
Yeah, it might have been that I had the old version on my desktop.

**Pull request merged**
