### PR TITLE
Incorporate changes discussed in last Nov. meeting

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
Changed .eln file to correspond to the results of the meeting last Nov.

### CODE REVIEW

**Review by NicolasCARPi — APPROVED** [review]
Works for me!

**Comment by FlorianRhiem** [comment]
Works with SampleDB

**Comment by jmanideep** [comment]
Works with Kadi4Mat.  

Though we(in Kadi4Mat) are not dealing with the author objects in the `ro-crate-metadata.json` file, just wondering if there is any particular reason for using list or array type for author objects.

**Comment by NicolasCARPi** [comment]
Yeah, regarding `author`, it's best to flatten it: author attributes only points to a node with an `@id`. This node is of `@type: Author`.

**Comment by SteffenBrinckmann** [comment]
Thanks everybody for the feedback.
- author(s): a paper can have multiple authors, data should be able, too; I guess.
- great that you can import it; (I am still having issues with some of yours.) 
We can discuss these during our next meeting

**Pull request merged**
