### PR TITLE
Update kadi4mat readme

### PR DESCRIPTION
**Pull request by jmanideep**

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Great!

Here is how it looks in eLab after import:
2022-07-07-152732_1736x741_scrot

Note: in eLab I removed the CSV and PDF export from eln archive export for several reasons:

* if one want a csv or pdf export they select pdf or csv for export
* making a pdf is expensive in terms of memory and computation (at least in elab), so when exporting thousands of items in .eln it helps a lot with time/memory
* pdfs are kinda heavy, especially PDF/A, so it reduces the size of the archive
* if you import/export several times you endup with multiple pdf
* while it is nice to have, a pdf doesn't bring new information
* as for the csv, I think it was never used by users anyway

That's just my point of view, I'm not advocating for anything, you do what you want, but I believe the .eln export should not contain other exports too, but rather focus on the metadata file which holds all the info, from which one can do what they want afterwards.

**Comment by NicolasCARPi** [comment]
It would be great if the sample record could contain tags and comments (if you have comments in kadi4mat)

**Comment by jmanideep** [comment]
In the examples, I somehow missed adding tags of a resource(for both records and collections), but in the eln archive export implementation, the tags are also included in the crate metadata JSON file. I will add tags to the sample record. And in the current version of kadi4mat, there is no possibility to add comments.

And I do remove QR and PDF export from adding it to the eln archive export. I just wanted to populate the files in the example.

**Review by NicolasCARPi — COMMENTED** [review]
I really like that this metadata json in readme gives us a proper diff to look at! Very conveniant.

**Comment by NicolasCARPi** [comment]
here is how it looks now: the tags are showing and the main content too! :)

2022-07-10-021108_1270x1052_scrot

**Pull request merged**
