### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
I updated the test:
- use latest version of ro-crate library from pip
- use schema that was supplied by Nico Carpi to verify
- use the ro-crate validator mentioned by @nicobrandt and @FlorianRhiem 
It produces a nice overview like https://github.com/SteffenBrinckmann/TheELNFileFormat/actions/runs/11921882162/attempts/1#summary-33226967243

Why have 4 tests: because they fulfill separate tasks:
- 2 tests The ELN consortium cannot influence, we cannot specify our ro-crate dialect (tests: pypi-rocrate and validator)
- the schema test allows us to use a schema to conveniently specify our dialect using data types
- param-metadata test allows us to fine-tune the requirements of the consortium; like the hierarchy requirements mentioned in #98. 

Also it is more impressive if 4 tests are successful, than 1 or 2.

### CODE REVIEW

**Comment by nicobrandt** [comment]
What about using https://github.com/crs4/rocrate-validator in addition to/instead of some of the checks? As we know, the library still has some issues but it seems to be steadily improving.

**Comment by SteffenBrinckmann** [comment]
Yes, good suggestion. I look into that

**Comment by FlorianRhiem** [comment]
Maybe this snippet helps, it's how I've added `rocrate_validator` to SampleDB tests:

```
result = rocrate_validator.services.validate({
    "profiles_path": rocrate_validator.utils.get_profiles_path(),
    "profile_identifier": "ro-crate",
    "requirement_severity": rocrate_validator.models.Severity.REQUIRED.name,
    "requirement_severity_only": False,
    "inherit_profiles": True,
    "verbose": True,
    "data_path": rocrate_dir,
    "ontology_path": None,
    "abort_on_first": False
})
result_dict = result.to_dict()
assert result_dict['issues'] == []
assert result_dict['passed']
```

**Comment by SteffenBrinckmann** [comment]
"rocrate-validator validate examples/kadi4mat/collections-example.zip" 
leads to "[FAILED] RO-Crate is not a valid ro-crate-1.1 !!!" which I totally do not agree with in its entirety.

**Comment by SteffenBrinckmann** [comment]
@FlorianRhiem can you write a test for it in the tests directory?

**Comment by FlorianRhiem** [comment]
> "rocrate-validator validate examples/kadi4mat/collections-example.zip" leads to "[FAILED] RO-Crate is not a valid ro-crate-1.1 !!!" which I totally do not agree with in its entirety.

I just ran the code from my post above with the unzipped collections-example from PR #100 and it passes. Maybe the issue is that it's the old .eln file or that it needs to be unzipped? If that doesn't help, I can look into writing a test tomorrow.

**Comment by nicobrandt** [comment]
Well our current example is indeed not valid :P You would have to try with the fixed ones in https://github.com/TheELNConsortium/TheELNFileFormat/pull/100

**Comment by nicobrandt** [comment]
Actually, that just reminded me that we also had trouble using the CLI on zipped files, even when using minimal examples, while the same content was valid after unzipping. @jmanideep wanted to create an issue for that in the validator repo.

**Comment by SteffenBrinckmann** [comment]
That was the issue: that thing cannot read into zip files. 
I wrote the first version of such a test and will likely publish it later today, if time permits.

**Comment by jmanideep** [comment]
An issue has been created in the `roc-validator` repository regarding  `validate` CLI command not working for validating ZIP files. Details can be found here: [Issue link](https://github.com/crs4/rocrate-validator/issues/43)

**Review by NicolasCARPi — APPROVED** [review]
:+1:

**Pull request merged**
