### PR TITLE
refresh elabftw examples

### PR DESCRIPTION
**Pull request by NicolasCARPi**
now Person/Comment/Mention are all "flattened", meaning they only point to an array of `@id`, and the node with the rest of the content is at the root.

### CODE REVIEW

**Comment by FlorianRhiem** [comment]
From how I understand RO-Crate, `@id` entries should be unique within the graph of a single ro-crate-metadata.json. That does not seem to be the case here, as there are two comments with an `@id` of `comment://2023-09-28T03%3A44%3A52%2B02%3A00` in `multiple-experiments.eln`. While two comments being posted at exactly the same time is less likely to come up in practice, it might be better to avoid the risk by adding a counter or something like that?

**Comment by NicolasCARPi** [comment]
@FlorianRhiem good spot! These comments are created by a "populate" script, that's why they are in the same second. While your remark is very much valid, I'll just consider this a non-issue for now, as the risk is pretty low IMHO.

**Comment by FlorianRhiem** [comment]
In that case, maybe the script could be altered slightly to avoid this issue in the example, so that it contains valid JSON-LD?

**Comment by NicolasCARPi** [comment]
I'll resubmit an archive without this issue.

**Pull request merged**
